/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FioAFioRouteImport } from './routes/fio-a-fio'
import { Route as M7RouteImport } from './routes/m7'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FioAFioRoute = FioAFioRouteImport.update({
  id: '/fio-a-fio',
  path: '/fio-a-fio',
  getParentRoute: () => rootRouteImport,
} as any)
const M7Route = M7RouteImport.update({
  id: '/m7',
  path: '/m7',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fio-a-fio': typeof FioAFioRoute
  '/m7': typeof M7Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fio-a-fio': typeof FioAFioRoute
  '/m7': typeof M7Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fio-a-fio': typeof FioAFioRoute
  '/m7': typeof M7Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fio-a-fio' | '/m7'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fio-a-fio' | '/m7'
  id: '__root__' | '/' | '/fio-a-fio' | '/m7'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FioAFioRoute: typeof FioAFioRoute
  M7Route: typeof M7Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fio-a-fio': {
      id: '/fio-a-fio'
      path: '/fio-a-fio'
      fullPath: '/fio-a-fio'
      preLoaderRoute: typeof FioAFioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m7': {
      id: '/m7'
      path: '/m7'
      fullPath: '/m7'
      preLoaderRoute: typeof M7RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FioAFioRoute: FioAFioRoute,
  M7Route: M7Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
